# Site settings
title: CoopClocker OSX
email: pro.balazs.tari@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  CoopClocker is a team-oriented countdown-based time-tracking tool.
  It's a small personal project I've started doing to create a tool for myself and my friends to use.
  That and to have a personal journey in management, design and structured implementation. Also, fun.
baseurl: "/coopclocker-osx" # the subpath of your site, e.g. /blog/
url: "http://t-ballz.github.io/coopclocker-osx" # the base hostname & protocol for your site
github_username:  t-ballz

# Build settings
markdown: kramdown
